namespace Challenge_thu_lam_DA
{
    partial class Form_Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_Login));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation2 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_signin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_signup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.tbx_username = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbx_password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_su = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.label3 = new System.Windows.Forms.Label();
            this.tbx_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.btn_signup);
            this.bunifuGradientPanel1.Controls.Add(this.btn_signin);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.label1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(201)))), ((int)(((byte)(54)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(201)))), ((int)(((byte)(54)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(113)))), ((int)(((byte)(16)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(113)))), ((int)(((byte)(16)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(749, 931);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 214;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(164, 30);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(428, 428);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Black", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(225, 426);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(307, 54);
            this.label1.TabIndex = 2;
            this.label1.Text = "Welcome back";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(178, 522);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(400, 60);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Lorem Ipsum is simply dummy text \r\nof the printing and typesetting industry.";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn_signin
            // 
            this.btn_signin.AllowAnimations = true;
            this.btn_signin.AllowMouseEffects = true;
            this.btn_signin.AllowToggling = false;
            this.btn_signin.AnimationSpeed = 200;
            this.btn_signin.AutoGenerateColors = false;
            this.btn_signin.AutoRoundBorders = false;
            this.btn_signin.AutoSizeLeftIcon = true;
            this.btn_signin.AutoSizeRightIcon = true;
            this.btn_signin.BackColor = System.Drawing.Color.Transparent;
            this.btn_signin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_signin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_signin.BackgroundImage")));
            this.btn_signin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signin.ButtonText = "SIGN IN";
            this.btn_signin.ButtonTextMarginLeft = 0;
            this.btn_signin.ColorContrastOnClick = 45;
            this.btn_signin.ColorContrastOnHover = 45;
            this.btn_signin.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_signin.CustomizableEdges = borderEdges6;
            this.btn_signin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_signin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_signin.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_signin.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_signin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_signin.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_signin.ForeColor = System.Drawing.Color.White;
            this.btn_signin.IconLeft = null;
            this.btn_signin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_signin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_signin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_signin.IconMarginLeft = 11;
            this.btn_signin.IconPadding = 10;
            this.btn_signin.IconRight = null;
            this.btn_signin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_signin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_signin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_signin.IconSize = 25;
            this.btn_signin.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_signin.IdleBorderRadius = 0;
            this.btn_signin.IdleBorderThickness = 0;
            this.btn_signin.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_signin.IdleIconLeftImage = null;
            this.btn_signin.IdleIconRightImage = null;
            this.btn_signin.IndicateFocus = false;
            this.btn_signin.Location = new System.Drawing.Point(150, 655);
            this.btn_signin.Name = "btn_signin";
            this.btn_signin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_signin.OnDisabledState.BorderRadius = 30;
            this.btn_signin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signin.OnDisabledState.BorderThickness = 2;
            this.btn_signin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_signin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_signin.OnDisabledState.IconLeftImage = null;
            this.btn_signin.OnDisabledState.IconRightImage = null;
            this.btn_signin.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btn_signin.onHoverState.BorderRadius = 30;
            this.btn_signin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signin.onHoverState.BorderThickness = 2;
            this.btn_signin.onHoverState.FillColor = System.Drawing.Color.White;
            this.btn_signin.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(196)))), ((int)(((byte)(50)))));
            this.btn_signin.onHoverState.IconLeftImage = null;
            this.btn_signin.onHoverState.IconRightImage = null;
            this.btn_signin.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_signin.OnIdleState.BorderRadius = 30;
            this.btn_signin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signin.OnIdleState.BorderThickness = 2;
            this.btn_signin.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn_signin.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_signin.OnIdleState.IconLeftImage = null;
            this.btn_signin.OnIdleState.IconRightImage = null;
            this.btn_signin.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_signin.OnPressedState.BorderRadius = 30;
            this.btn_signin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signin.OnPressedState.BorderThickness = 2;
            this.btn_signin.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn_signin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_signin.OnPressedState.IconLeftImage = null;
            this.btn_signin.OnPressedState.IconRightImage = null;
            this.btn_signin.Size = new System.Drawing.Size(206, 67);
            this.btn_signin.TabIndex = 4;
            this.btn_signin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_signin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_signin.TextMarginLeft = 0;
            this.btn_signin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_signin.UseDefaultRadiusAndThickness = true;
            this.btn_signin.Click += new System.EventHandler(this.btn_signin_Click);
            // 
            // btn_signup
            // 
            this.btn_signup.AllowAnimations = true;
            this.btn_signup.AllowMouseEffects = true;
            this.btn_signup.AllowToggling = false;
            this.btn_signup.AnimationSpeed = 200;
            this.btn_signup.AutoGenerateColors = false;
            this.btn_signup.AutoRoundBorders = false;
            this.btn_signup.AutoSizeLeftIcon = true;
            this.btn_signup.AutoSizeRightIcon = true;
            this.btn_signup.BackColor = System.Drawing.Color.Transparent;
            this.btn_signup.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_signup.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_signup.BackgroundImage")));
            this.btn_signup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signup.ButtonText = "SIGN UP";
            this.btn_signup.ButtonTextMarginLeft = 0;
            this.btn_signup.ColorContrastOnClick = 45;
            this.btn_signup.ColorContrastOnHover = 45;
            this.btn_signup.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_signup.CustomizableEdges = borderEdges5;
            this.btn_signup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_signup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_signup.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_signup.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_signup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_signup.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_signup.ForeColor = System.Drawing.Color.White;
            this.btn_signup.IconLeft = null;
            this.btn_signup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_signup.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_signup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_signup.IconMarginLeft = 11;
            this.btn_signup.IconPadding = 10;
            this.btn_signup.IconRight = null;
            this.btn_signup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_signup.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_signup.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_signup.IconSize = 25;
            this.btn_signup.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_signup.IdleBorderRadius = 0;
            this.btn_signup.IdleBorderThickness = 0;
            this.btn_signup.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_signup.IdleIconLeftImage = null;
            this.btn_signup.IdleIconRightImage = null;
            this.btn_signup.IndicateFocus = false;
            this.btn_signup.Location = new System.Drawing.Point(372, 655);
            this.btn_signup.Name = "btn_signup";
            this.btn_signup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_signup.OnDisabledState.BorderRadius = 30;
            this.btn_signup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signup.OnDisabledState.BorderThickness = 2;
            this.btn_signup.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_signup.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_signup.OnDisabledState.IconLeftImage = null;
            this.btn_signup.OnDisabledState.IconRightImage = null;
            this.btn_signup.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btn_signup.onHoverState.BorderRadius = 30;
            this.btn_signup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signup.onHoverState.BorderThickness = 2;
            this.btn_signup.onHoverState.FillColor = System.Drawing.Color.White;
            this.btn_signup.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(196)))), ((int)(((byte)(50)))));
            this.btn_signup.onHoverState.IconLeftImage = null;
            this.btn_signup.onHoverState.IconRightImage = null;
            this.btn_signup.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_signup.OnIdleState.BorderRadius = 30;
            this.btn_signup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signup.OnIdleState.BorderThickness = 2;
            this.btn_signup.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn_signup.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_signup.OnIdleState.IconLeftImage = null;
            this.btn_signup.OnIdleState.IconRightImage = null;
            this.btn_signup.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_signup.OnPressedState.BorderRadius = 30;
            this.btn_signup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_signup.OnPressedState.BorderThickness = 2;
            this.btn_signup.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn_signup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_signup.OnPressedState.IconLeftImage = null;
            this.btn_signup.OnPressedState.IconRightImage = null;
            this.btn_signup.Size = new System.Drawing.Size(206, 67);
            this.btn_signup.TabIndex = 5;
            this.btn_signup.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_signup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_signup.TextMarginLeft = 0;
            this.btn_signup.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_signup.UseDefaultRadiusAndThickness = true;
            this.btn_signup.Click += new System.EventHandler(this.btn_signup_Click);
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = true;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Controls.Add(this.tabPage2);
            this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuPages1.Location = new System.Drawing.Point(750, 0);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.tabPage2;
            this.bunifuPages1.PageIndex = 1;
            this.bunifuPages1.PageName = "tabPage2";
            this.bunifuPages1.PageTitle = "tabPage2";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(700, 931);
            this.bunifuPages1.TabIndex = 2;
            animation2.AnimateOnlyDifferences = true;
            animation2.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.BlindCoeff")));
            animation2.LeafCoeff = 0F;
            animation2.MaxTime = 1F;
            animation2.MinTime = 0F;
            animation2.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.MosaicCoeff")));
            animation2.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation2.MosaicShift")));
            animation2.MosaicSize = 0;
            animation2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation2.RotateCoeff = 0F;
            animation2.RotateLimit = 0F;
            animation2.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.ScaleCoeff")));
            animation2.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation2.SlideCoeff")));
            animation2.TimeCoeff = 0F;
            animation2.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation2;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.VertSlide;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.btn_su);
            this.tabPage1.Controls.Add(this.tbx_password);
            this.tabPage1.Controls.Add(this.tbx_username);
            this.tabPage1.Controls.Add(this.bunifuSeparator1);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(692, 898);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage1.Click += new System.EventHandler(this.tabPage1_Click);
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.tbx_email);
            this.tabPage2.Controls.Add(this.bunifuButton1);
            this.tabPage2.Controls.Add(this.btn_password);
            this.tabPage2.Controls.Add(this.bunifuTextBox2);
            this.tabPage2.Controls.Add(this.bunifuSeparator2);
            this.tabPage2.Controls.Add(this.label3);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(692, 898);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 26F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.label2.Location = new System.Drawing.Point(243, 129);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(224, 70);
            this.label2.TabIndex = 6;
            this.label2.Text = "SIGN IN";
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 3;
            this.bunifuSeparator1.Location = new System.Drawing.Point(225, 210);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(261, 19);
            this.bunifuSeparator1.TabIndex = 7;
            this.bunifuSeparator1.Click += new System.EventHandler(this.bunifuSeparator1_Click);
            // 
            // tbx_username
            // 
            this.tbx_username.AcceptsReturn = false;
            this.tbx_username.AcceptsTab = false;
            this.tbx_username.AnimationSpeed = 200;
            this.tbx_username.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_username.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_username.AutoSizeHeight = true;
            this.tbx_username.BackColor = System.Drawing.Color.Transparent;
            this.tbx_username.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_username.BackgroundImage")));
            this.tbx_username.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_username.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_username.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_username.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbx_username.BorderRadius = 1;
            this.tbx_username.BorderThickness = 2;
            this.tbx_username.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbx_username.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_username.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_username.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbx_username.DefaultText = "";
            this.tbx_username.FillColor = System.Drawing.Color.White;
            this.tbx_username.HideSelection = true;
            this.tbx_username.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbx_username.IconLeft")));
            this.tbx_username.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_username.IconPadding = 10;
            this.tbx_username.IconRight = null;
            this.tbx_username.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_username.Lines = new string[0];
            this.tbx_username.Location = new System.Drawing.Point(95, 340);
            this.tbx_username.MaxLength = 32767;
            this.tbx_username.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_username.Modified = false;
            this.tbx_username.Multiline = false;
            this.tbx_username.Name = "tbx_username";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_username.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_username.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_username.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_username.OnIdleState = stateProperties24;
            this.tbx_username.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_username.PasswordChar = '\0';
            this.tbx_username.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbx_username.PlaceholderText = "Enter username";
            this.tbx_username.ReadOnly = false;
            this.tbx_username.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_username.SelectedText = "";
            this.tbx_username.SelectionLength = 0;
            this.tbx_username.SelectionStart = 0;
            this.tbx_username.ShortcutsEnabled = true;
            this.tbx_username.Size = new System.Drawing.Size(504, 62);
            this.tbx_username.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_username.TabIndex = 8;
            this.tbx_username.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_username.TextMarginBottom = 0;
            this.tbx_username.TextMarginLeft = 3;
            this.tbx_username.TextMarginTop = 1;
            this.tbx_username.TextPlaceholder = "Enter username";
            this.tbx_username.UseSystemPasswordChar = false;
            this.tbx_username.WordWrap = true;
            // 
            // tbx_password
            // 
            this.tbx_password.AcceptsReturn = false;
            this.tbx_password.AcceptsTab = false;
            this.tbx_password.AnimationSpeed = 200;
            this.tbx_password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_password.AutoSizeHeight = true;
            this.tbx_password.BackColor = System.Drawing.Color.Transparent;
            this.tbx_password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_password.BackgroundImage")));
            this.tbx_password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_password.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbx_password.BorderRadius = 1;
            this.tbx_password.BorderThickness = 2;
            this.tbx_password.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbx_password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_password.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbx_password.DefaultText = "";
            this.tbx_password.FillColor = System.Drawing.Color.White;
            this.tbx_password.HideSelection = true;
            this.tbx_password.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbx_password.IconLeft")));
            this.tbx_password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_password.IconPadding = 10;
            this.tbx_password.IconRight = null;
            this.tbx_password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_password.Lines = new string[0];
            this.tbx_password.Location = new System.Drawing.Point(95, 461);
            this.tbx_password.MaxLength = 32767;
            this.tbx_password.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_password.Modified = false;
            this.tbx_password.Multiline = false;
            this.tbx_password.Name = "tbx_password";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_password.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_password.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties27.FillColor = System.Drawing.Color.White;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_password.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_password.OnIdleState = stateProperties28;
            this.tbx_password.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_password.PasswordChar = '\0';
            this.tbx_password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbx_password.PlaceholderText = "Enter password";
            this.tbx_password.ReadOnly = false;
            this.tbx_password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_password.SelectedText = "";
            this.tbx_password.SelectionLength = 0;
            this.tbx_password.SelectionStart = 0;
            this.tbx_password.ShortcutsEnabled = true;
            this.tbx_password.Size = new System.Drawing.Size(504, 62);
            this.tbx_password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_password.TabIndex = 9;
            this.tbx_password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_password.TextMarginBottom = 0;
            this.tbx_password.TextMarginLeft = 3;
            this.tbx_password.TextMarginTop = 1;
            this.tbx_password.TextPlaceholder = "Enter password";
            this.tbx_password.UseSystemPasswordChar = true;
            this.tbx_password.WordWrap = true;
            // 
            // btn_su
            // 
            this.btn_su.AllowAnimations = true;
            this.btn_su.AllowMouseEffects = true;
            this.btn_su.AllowToggling = false;
            this.btn_su.AnimationSpeed = 200;
            this.btn_su.AutoGenerateColors = false;
            this.btn_su.AutoRoundBorders = false;
            this.btn_su.AutoSizeLeftIcon = true;
            this.btn_su.AutoSizeRightIcon = true;
            this.btn_su.BackColor = System.Drawing.Color.Transparent;
            this.btn_su.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_su.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_su.BackgroundImage")));
            this.btn_su.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_su.ButtonText = "SIGN IN";
            this.btn_su.ButtonTextMarginLeft = 0;
            this.btn_su.ColorContrastOnClick = 45;
            this.btn_su.ColorContrastOnHover = 45;
            this.btn_su.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_su.CustomizableEdges = borderEdges7;
            this.btn_su.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_su.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_su.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_su.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_su.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_su.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_su.ForeColor = System.Drawing.Color.Transparent;
            this.btn_su.IconLeft = null;
            this.btn_su.IconLeftAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.btn_su.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_su.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_su.IconMarginLeft = 11;
            this.btn_su.IconPadding = 10;
            this.btn_su.IconRight = null;
            this.btn_su.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_su.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_su.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_su.IconSize = 25;
            this.btn_su.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_su.IdleBorderRadius = 0;
            this.btn_su.IdleBorderThickness = 0;
            this.btn_su.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_su.IdleIconLeftImage = null;
            this.btn_su.IdleIconRightImage = null;
            this.btn_su.IndicateFocus = false;
            this.btn_su.Location = new System.Drawing.Point(393, 574);
            this.btn_su.Name = "btn_su";
            this.btn_su.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_su.OnDisabledState.BorderRadius = 30;
            this.btn_su.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_su.OnDisabledState.BorderThickness = 3;
            this.btn_su.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_su.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_su.OnDisabledState.IconLeftImage = null;
            this.btn_su.OnDisabledState.IconRightImage = null;
            this.btn_su.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.onHoverState.BorderRadius = 30;
            this.btn_su.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_su.onHoverState.BorderThickness = 3;
            this.btn_su.onHoverState.FillColor = System.Drawing.Color.White;
            this.btn_su.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.onHoverState.IconLeftImage = null;
            this.btn_su.onHoverState.IconRightImage = null;
            this.btn_su.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.OnIdleState.BorderRadius = 30;
            this.btn_su.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_su.OnIdleState.BorderThickness = 3;
            this.btn_su.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btn_su.OnIdleState.IconLeftImage = null;
            this.btn_su.OnIdleState.IconRightImage = null;
            this.btn_su.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.OnPressedState.BorderRadius = 30;
            this.btn_su.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_su.OnPressedState.BorderThickness = 3;
            this.btn_su.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btn_su.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_su.OnPressedState.IconLeftImage = null;
            this.btn_su.OnPressedState.IconRightImage = null;
            this.btn_su.Size = new System.Drawing.Size(206, 67);
            this.btn_su.TabIndex = 6;
            this.btn_su.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_su.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_su.TextMarginLeft = 0;
            this.btn_su.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_su.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "SIGN UP";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges8;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(392, 652);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 30;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 3;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.bunifuButton1.onHoverState.BorderRadius = 30;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 3;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(196)))), ((int)(((byte)(50)))));
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 30;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 3;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 30;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 3;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(206, 67);
            this.bunifuButton1.TabIndex = 10;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // btn_password
            // 
            this.btn_password.AcceptsReturn = false;
            this.btn_password.AcceptsTab = false;
            this.btn_password.AnimationSpeed = 200;
            this.btn_password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btn_password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btn_password.AutoSizeHeight = true;
            this.btn_password.BackColor = System.Drawing.Color.Transparent;
            this.btn_password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_password.BackgroundImage")));
            this.btn_password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btn_password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_password.BorderColorIdle = System.Drawing.Color.Silver;
            this.btn_password.BorderRadius = 1;
            this.btn_password.BorderThickness = 2;
            this.btn_password.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.btn_password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btn_password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btn_password.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_password.DefaultText = "";
            this.btn_password.FillColor = System.Drawing.Color.White;
            this.btn_password.HideSelection = true;
            this.btn_password.IconLeft = ((System.Drawing.Image)(resources.GetObject("btn_password.IconLeft")));
            this.btn_password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btn_password.IconPadding = 10;
            this.btn_password.IconRight = null;
            this.btn_password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btn_password.Lines = new string[0];
            this.btn_password.Location = new System.Drawing.Point(94, 539);
            this.btn_password.MaxLength = 32767;
            this.btn_password.MinimumSize = new System.Drawing.Size(1, 1);
            this.btn_password.Modified = false;
            this.btn_password.Multiline = false;
            this.btn_password.Name = "btn_password";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btn_password.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btn_password.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties31.FillColor = System.Drawing.Color.White;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btn_password.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btn_password.OnIdleState = stateProperties32;
            this.btn_password.Padding = new System.Windows.Forms.Padding(3);
            this.btn_password.PasswordChar = '\0';
            this.btn_password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.btn_password.PlaceholderText = "Enter password";
            this.btn_password.ReadOnly = false;
            this.btn_password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btn_password.SelectedText = "";
            this.btn_password.SelectionLength = 0;
            this.btn_password.SelectionStart = 0;
            this.btn_password.ShortcutsEnabled = true;
            this.btn_password.Size = new System.Drawing.Size(504, 62);
            this.btn_password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btn_password.TabIndex = 14;
            this.btn_password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btn_password.TextMarginBottom = 0;
            this.btn_password.TextMarginLeft = 3;
            this.btn_password.TextMarginTop = 1;
            this.btn_password.TextPlaceholder = "Enter password";
            this.btn_password.UseSystemPasswordChar = true;
            this.btn_password.WordWrap = true;
            // 
            // bunifuTextBox2
            // 
            this.bunifuTextBox2.AcceptsReturn = false;
            this.bunifuTextBox2.AcceptsTab = false;
            this.bunifuTextBox2.AnimationSpeed = 200;
            this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox2.AutoSizeHeight = true;
            this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
            this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox2.BorderRadius = 1;
            this.bunifuTextBox2.BorderThickness = 2;
            this.bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox2.DefaultText = "";
            this.bunifuTextBox2.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox2.HideSelection = true;
            this.bunifuTextBox2.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.IconLeft")));
            this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.IconPadding = 10;
            this.bunifuTextBox2.IconRight = null;
            this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.Lines = new string[0];
            this.bunifuTextBox2.Location = new System.Drawing.Point(94, 340);
            this.bunifuTextBox2.MaxLength = 32767;
            this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox2.Modified = false;
            this.bunifuTextBox2.Multiline = false;
            this.bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox2.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties35.FillColor = System.Drawing.Color.White;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnIdleState = stateProperties36;
            this.bunifuTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox2.PasswordChar = '\0';
            this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox2.PlaceholderText = "Enter username";
            this.bunifuTextBox2.ReadOnly = false;
            this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox2.SelectedText = "";
            this.bunifuTextBox2.SelectionLength = 0;
            this.bunifuTextBox2.SelectionStart = 0;
            this.bunifuTextBox2.ShortcutsEnabled = true;
            this.bunifuTextBox2.Size = new System.Drawing.Size(504, 62);
            this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox2.TabIndex = 13;
            this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox2.TextMarginBottom = 0;
            this.bunifuTextBox2.TextMarginLeft = 3;
            this.bunifuTextBox2.TextMarginTop = 1;
            this.bunifuTextBox2.TextPlaceholder = "Enter username";
            this.bunifuTextBox2.UseSystemPasswordChar = false;
            this.bunifuTextBox2.WordWrap = true;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 3;
            this.bunifuSeparator2.Location = new System.Drawing.Point(224, 210);
            this.bunifuSeparator2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(261, 19);
            this.bunifuSeparator2.TabIndex = 12;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 26F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.label3.Location = new System.Drawing.Point(242, 129);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(237, 70);
            this.label3.TabIndex = 11;
            this.label3.Text = "SIGN UP";
            // 
            // tbx_email
            // 
            this.tbx_email.AcceptsReturn = false;
            this.tbx_email.AcceptsTab = false;
            this.tbx_email.AnimationSpeed = 200;
            this.tbx_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_email.AutoSizeHeight = true;
            this.tbx_email.BackColor = System.Drawing.Color.Transparent;
            this.tbx_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_email.BackgroundImage")));
            this.tbx_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_email.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbx_email.BorderRadius = 1;
            this.tbx_email.BorderThickness = 2;
            this.tbx_email.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbx_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbx_email.DefaultText = "";
            this.tbx_email.FillColor = System.Drawing.Color.White;
            this.tbx_email.HideSelection = true;
            this.tbx_email.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbx_email.IconLeft")));
            this.tbx_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.IconPadding = 10;
            this.tbx_email.IconRight = null;
            this.tbx_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.Lines = new string[0];
            this.tbx_email.Location = new System.Drawing.Point(95, 442);
            this.tbx_email.MaxLength = 32767;
            this.tbx_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_email.Modified = false;
            this.tbx_email.Multiline = false;
            this.tbx_email.Name = "tbx_email";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_email.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties39.FillColor = System.Drawing.Color.White;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnIdleState = stateProperties40;
            this.tbx_email.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_email.PasswordChar = '\0';
            this.tbx_email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbx_email.PlaceholderText = "Enter email";
            this.tbx_email.ReadOnly = false;
            this.tbx_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_email.SelectedText = "";
            this.tbx_email.SelectionLength = 0;
            this.tbx_email.SelectionStart = 0;
            this.tbx_email.ShortcutsEnabled = true;
            this.tbx_email.Size = new System.Drawing.Size(504, 62);
            this.tbx_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_email.TabIndex = 15;
            this.tbx_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_email.TextMarginBottom = 0;
            this.tbx_email.TextMarginLeft = 3;
            this.tbx_email.TextMarginTop = 1;
            this.tbx_email.TextPlaceholder = "Enter email";
            this.tbx_email.UseSystemPasswordChar = false;
            this.tbx_email.WordWrap = true;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Form_Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1450, 931);
            this.Controls.Add(this.bunifuPages1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_Login";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form_login";
            this.Load += new System.EventHandler(this.Form_Login_Load);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_signin;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_signup;
        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_username;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_su;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_password;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_email;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuTextBox btn_password;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
    }
}

